#!/usr/bin/env python
# -*- coding: UTF-8 -*-
# vim: autoindent expandtab tabstop=4 sw=4 sts=4 filetype=python

import connect_spice_client


if __name__ == "__main__":
    # logging.basicConfig(level=logging.DEBUG)
    connect_spice_client.connect_spice_client().shutdown_vm_action_sequence()
