#!/bin/bash

# FIXME: HEADER

# Global variables
declare -a ARGV
declare -a ssh_opts
declare -a remote_cmdline
declare -i CMDLINE_AVAILABLE=0
declare	   TC
declare	   TC_RAW

source $(dirname $(readlink -e ${BASH_SOURCE}))/utils.sh

display_usage() {
	cat 1>&2 <<-'EndOfHelpText'
	Usage:

	# interactive shell:
	tc_ssh <thinclient> [ssh-args]                    

	# execute remote command
	tc_ssh <thinclient> [ssh-args] -- remote_command

	
	tc_ssh is used for ssh remote access to thinclients.

	It can be used to open an interactive shell, or
	to execute remote commands.

	tc_ssh is part of the amoothei-tc-tools collection.

	Amoothei-vdi is a virtual desktop infrastructure
	solution based on RHEV / Ovirt.

	Documentation: see amoothei-tc-tools.md.
EndOfHelpText

	exit 1;
}

ARGV=( $* )

source_configfiles
parse_cmdline
process_thinclient_arg

debug ssh $SSH_GLOBAL_OPTS ${ssh_opts[@]} $TC -- "${remote_cmdline[@]}"
ssh $SSH_GLOBAL_OPTS ${ssh_opts[@]} $TC -- "${remote_cmdline[@]}"

RETCODE=$?

if [[ $RETCODE -ne 0 ]]; then
	error_msg "Thinclient $TC: SSH return code: $RETCODE"
fi

exit $RETCODE

