#!/bin/bash

# Copyright (c) 2013-2016, Adfinis SyGroup AG
#
# This file is part of Virtesk VDI.
#
# Virtesk VDI is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Virtesk VDI is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Virtesk VDI.  If not, see <http://www.gnu.org/licenses/>.

# Global variables
declare -a ARGV
declare -a ssh_opts
declare -a remote_cmdline
declare -i CMDLINE_AVAILABLE=0

source $(dirname $(readlink -e ${BASH_SOURCE}))/utils.sh

display_usage() {
	cat 1>&2 <<-'EndOfHelpText'
	Usage:

	tc_rollout_kexec <thinclient>


	tc_rollout_kexec is used to roll out thinclients
	using ssh and kexec.

	It is useful for re-installation of already
	installed thinclients.

	tc_rollout_kexec is part of the virtesk-tc-tools collection.

	Amoothei-vdi is a virtual desktop infrastructure
	solution based on RHEV / Ovirt.

	Documentation: see doc/virtesk-tc-tools.rst .
EndOfHelpText

	exit 1;
}

ARGV=( $* )

source_configfiles
parse_cmdline_simple "$1"

debug tc_ssh "$1" -- "$ROLLOUT_CMDLINE"
tc_ssh "$1" -- "$ROLLOUT_CMDLINE"

RETCODE=$?
exit $RETCODE

