#!/bin/bash

# Copyright (c) 2013-2016, Adfinis SyGroup AG
#
# This file is part of Virtesk VDI.
#
# Virtesk VDI is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Virtesk VDI is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Virtesk VDI.  If not, see <http://www.gnu.org/licenses/>.

# Global variables
declare -a ARGV
declare -a ssh_opts
declare -a remote_cmdline
declare -i CMDLINE_AVAILABLE=0
declare	   TC
declare	   TC_RAW

source $(dirname $(readlink -e ${BASH_SOURCE}))/utils.sh

display_usage() {
	cat 1>&2 <<-'EndOfHelpText'
	Usage:

	# interactive shell:
	tc_ssh <thinclient> [ssh-args]                    

	# execute remote command
	tc_ssh <thinclient> [ssh-args] -- remote_command

	
	tc_ssh is used for ssh remote access to thinclients.

	It can be used to open an interactive shell, or
	to execute remote commands.

	tc_ssh is part of the virtesk-tc-tools collection.

	Amoothei-vdi is a virtual desktop infrastructure
	solution based on RHEV / Ovirt.

	Documentation: see doc/virtesk-tc-tools.rst .
EndOfHelpText

	exit 1;
}

ARGV=( $* )

source_configfiles
parse_cmdline
process_thinclient_arg

debug ssh $SSH_GLOBAL_OPTS ${ssh_opts[@]} $TC -- "${remote_cmdline[@]}"
ssh $SSH_GLOBAL_OPTS ${ssh_opts[@]} $TC -- "${remote_cmdline[@]}"

RETCODE=$?

if [[ $RETCODE -ne 0 ]]; then
	error_msg "Thinclient $TC: SSH return code: $RETCODE"
fi

exit $RETCODE

